title:              Danilo Brandão
email:              brandaodanilog@gmail.com
description:        I'm a data scientist and engineer based in Porto. I like to automate stuff and find interesting information hiding in data.
author:             Danilo Brandão
baseurl:            ""
url:                "https://danilogb.github.io"

# Social Profiles
# twitter_username:   SBootstrap
github_username:    danilogb
# facebook_username:  StartBootstrap
# instagram_username:  
linkedin_username:  dgbrandao

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           4
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
