title: Danilo Brandão
description: Hello! I'm Danilo Brandão, a data scientist and engineer based in Porto, Portugal, who likes to automate stuff and find meaning in data.
social_media_share_image: /images/01.jpg
disqus-identifier:
google-analytics: